apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: direct
    orgId: 1
    default: true
    uid: 1037
    url: http://prometheus:9090
